repos:
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.6  # or specific git tag
  hooks:
    - id: shellcheck
    - id: shfmt

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.31.1
  hooks:
  - id: markdownlint

- repo: https://github.com/streetsidesoftware/cspell-cli
  rev: v5.9.0
  hooks:
  - id: cspell

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0  # Use the ref you want to point at
  hooks:
   -   id: check-yaml
